### ISSUE TITLE
Section numbers are broken

### ISSUE THREAD

**Issue by tmcw** [openlawdc/formats#1]
See http://tex.stackexchange.com/questions/109614/completely-disabling-the-section-step-counter

**Comment by JoshData** [comment]
Fastest workaround might be to use \section\* which creates a section w/o numbering. The only drawback that I can think of is you'll need to create a table of contents by hand, since \section*'s aren't included in the TOC.

**Comment by tmcw** [comment]
yep, thx. been going that route and next commit will adopt that style

**Comment by tmcw** [comment]
Fixed in 4cec7ccea33a013aac8a7492483bb0652906c84e
