### ISSUE TITLE
Print

### ISSUE THREAD

**Issue by tmcw** [openlawdc/formats#4]
Recently stopped in the library, and saw that DC bought itself a [book printing machine](http://dclibrary.org/digitalcommons/ebm). I've been out of the dc code game for a little bit but it would be awesome to see if we could reformat the open copy into something anyone could print for themselves, for cheap.

/cc @JoshData @konklone @vzvenyach

**Comment by konklone** [comment]
Looks like you just need a PDF:

```
What kind of binding options are there? 
The machine makes perfect-bound paperback books.

Can my book have photos or illustrations? 
Yes, whatever is in the PDF you submit is what prints. 

Can I print in color?
The cover can be in color, interior pages print in black and white.

How do I format my book?
The Intro to EBM workshop will cover that information.

Will you proofread my book?
We do not offer proofreading services.
```

**Comment by vdavez** [comment]
I wish they proofread... might make my job easier. _zing_

**Comment by schmod** [comment]
Well, this would certainly make the project come full-circle....

**Comment by JoshData** [comment]
Except... Who reads books?
